[server]
server_os = "fedora"
mode = "development"
domain = "localhost"
new_domain = "false"
user_email = "test@test.com"
reset = "false"
default_lang = "en"
theme = "simple"

[server.development]
http_port = ":8080"
https_port = ":8443"

[server.production]
http_port = ":80"
https_port = ":443"

[database]
host = "localhost"
name = "tukosmo"
user = "tukosmouser"
password = "1234"

[modules.blog]
enabled = "yes"
web_enabled = "yes"

[modules.gallery]
enabled = "yes"
web_enabled = "yes"

[modules.faq]
enabled = "yes"
web_enabled = "yes"

[modules.payments]
enabled = "yes"
web_enabled = "yes"

[modules.subscriptions]
enabled = "yes"
web_enabled = "yes"

[modules.shop]
enabled = "yes"
web_enabled = "yes"
